/**
 * Textes juridiques, convertis depuis les documents Word fournis.
 *
 * Le contenu n'est pas réécrit : chaque paragraphe est repris mot pour mot.
 * Seule la structure est reconstituée — titres, paragraphes, listes — pour
 * que la page soit lisible et correctement interprétée par les moteurs.
 *
 * Pour mettre à jour un texte, repartir du document Word : c'est lui qui fait foi.
 */

export type LegalBlock = { k: "h2" | "h3" | "h4" | "p" | "li"; t: string };

export type LegalDoc = {
  slug: string;
  title: string;
  description: string;
  updated: string;
  blocks: LegalBlock[];
};

export const legalDocs: Record<string, LegalDoc> = {
  "notice-ia": {
    slug: "notice-ia",
    title: "Notice d'utilisation de l'IA",
    description: "Comment Helpify utilise l'intelligence artificielle dans l'analyse des candidatures, et quels sont vos droits.",
    updated: "Dernière mise à jour : 06/06/2026",
    blocks: [
      { k: "p", t: "Helpify utilise des technologies d’intelligence artificielle afin d’assister les recruteurs dans l’analyse des candidatures et l’évaluation de l’adéquation entre un profil et un poste." },
      { k: "h3", t: "Finalité du système" },
      { k: "p", t: "Le système d’intelligence artificielle utilisé par Helpify a pour objectif d’aider les recruteurs à mieux comprendre les candidatures reçues, à structurer leur analyse et à identifier les éléments pertinents au regard des besoins de recrutement définis." },
      { k: "p", t: "Le système ne remplace pas le recruteur et n’a pas vocation à prendre des décisions de recrutement de manière autonome." },
      { k: "h3", t: "Données analysées" },
      { k: "p", t: "Le système peut analyser notamment :" },
      { k: "li", t: "les informations figurant dans le CV ;" },
      { k: "li", t: "les réponses écrites fournies par le candidat ;" },
      { k: "li", t: "les réponses orales et leurs transcriptions ;" },
      { k: "li", t: "les informations relatives au poste à pourvoir ;" },
      { k: "li", t: "les critères d’évaluation définis par l’entreprise ou le cabinet de recrutement." },
      { k: "h3", t: "Résultats générés" },
      { k: "p", t: "Le système peut produire :" },
      { k: "li", t: "un score global d’adéquation au poste ;" },
      { k: "li", t: "des scores par compétence ou critère évalué ;" },
      { k: "li", t: "un résumé structuré du profil ;" },
      { k: "li", t: "des points d’attention ou axes de vigilance ;" },
      { k: "li", t: "des suggestions de questions complémentaires ;" },
      { k: "li", t: "des explications générales relatives aux résultats générés." },
      { k: "p", t: "Ces résultats constituent exclusivement une aide à la décision." },
      { k: "h3", t: "Fonctionnement général" },
      { k: "p", t: "Les analyses sont réalisées à partir de l’adéquation entre les compétences, expériences, réponses et éléments professionnels communiqués par le candidat et les critères définis pour le poste concerné." },
      { k: "p", t: "Selon la configuration retenue par l’entreprise utilisatrice, les évaluations peuvent s’appuyer soit sur des méthodologies proposées par Helpify, soit sur des critères, questions ou référentiels définis directement par le recruteur." },
      { k: "h3", t: "Réduction des biais" },
      { k: "p", t: "Helpify met en œuvre des mesures destinées à réduire la prise en compte d’informations non pertinentes pour l’évaluation professionnelle." },
      { k: "p", t: "Lorsque cela est techniquement possible, certaines données d’identification ou informations sensibles peuvent être exclues ou limitées lors des phases d’analyse automatisée." },
      { k: "p", t: "Les évaluations sont conçues pour se concentrer sur les éléments professionnels pertinents au regard du poste concerné." },
      { k: "h3", t: "Supervision humaine" },
      { k: "p", t: "Aucune décision d’embauche, de rejet ou de classement définitif n’est prise automatiquement par le système." },
      { k: "p", t: "Les recruteurs conservent à tout moment la maîtrise du processus de recrutement, l’accès aux informations sources et la responsabilité de la décision finale." },
      { k: "h3", t: "Limites du système" },
      { k: "p", t: "Les résultats générés par le système reposent sur les informations disponibles au moment de l’analyse." },
      { k: "p", t: "Ils peuvent comporter des imprécisions et doivent toujours être interprétés avec discernement par un recruteur humain." },
      { k: "h3", t: "Contact" },
      { k: "p", t: "Pour toute question relative à l’utilisation de l’intelligence artificielle au sein de la plateforme Helpify, vous pouvez contacter :" },
      { k: "p", t: "support@helpify-ai.fr" },
    ],
  },
  "politique-de-confidentialite": {
    slug: "politique-de-confidentialite",
    title: "Politique de confidentialité",
    description: "Comment Helpify traite les données personnelles des candidats et des utilisateurs de la plateforme.",
    updated: "Dernière mise à jour : 6 octobre 2026",
    blocks: [
      { k: "p", t: "La société Helpify, société par actions simplifiée, dont le siège social est situé 59 rue de Ponthieu, 75008 Paris, France (ci-après « Helpify », « nous »), accorde une importance essentielle à la protection des données personnelles et de la vie privée dans le cadre de l’utilisation de sa plateforme SaaS d’intelligence artificielle appliquée au recrutement." },
      { k: "p", t: "La présente politique a pour objet d’informer de manière transparente l’ensemble des personnes concernées (candidats, utilisateurs de la plateforme et entreprises clientes) sur les traitements de données réalisés via la solution Helpify." },
      { k: "h2", t: "1. RÔLES DES ACTEURS (RESPONSABILITÉ RGPD)" },
      { k: "p", t: "Dans le cadre de l’utilisation de la plateforme Helpify :" },
      { k: "h4", t: "1.1 Entreprises clientes (recruteurs)" },
      { k: "p", t: "Les entreprises clientes déterminent les finalités et moyens des traitements de données réalisés dans le cadre de leurs recrutements." },
      { k: "p", t: "Elles agissent en qualité de responsables de traitement au sens du RGPD." },
      { k: "h4", t: "1.2 Helpify" },
      { k: "p", t: "Helpify agit en qualité de :" },
      { k: "li", t: "sous-traitant pour le compte des entreprises clientes concernant les données de recrutement," },
      { k: "li", t: "responsable de traitement pour ses propres données (gestion de compte, sécurité, facturation, support)." },
      { k: "h4", t: "1.3 Candidats" },
      { k: "p", t: "Les candidats interagissent avec la plateforme dans le cadre de processus de recrutement mis en place par les entreprises clientes." },
      { k: "h2", t: "2. DONNÉES PERSONNELLES TRAITÉES" },
      { k: "p", t: "Nous collectons et traitons les catégories de données suivantes :" },
      { k: "h3", t: "2.1 Données des candidats" },
      { k: "li", t: "Identité : nom, prénom" },
      { k: "li", t: "Coordonnées : email, téléphone" },
      { k: "li", t: "Données professionnelles : CV, expérience, formation, compétences" },
      { k: "li", t: "Données issues des échanges :" },
      { k: "li", t: "réponses écrites" },
      { k: "li", t: "enregistrements audio" },
      { k: "li", t: "transcriptions automatiques" },
      { k: "li", t: "Données d’analyse :" },
      { k: "li", t: "synthèses générées" },
      { k: "li", t: "scoring" },
      { k: "li", t: "éléments de qualification" },
      { k: "li", t: "historique d’interaction" },
      { k: "h3", t: "2.2 Données des utilisateurs (recruteurs / RH / managers)" },
      { k: "li", t: "nom, prénom" },
      { k: "li", t: "email professionnel" },
      { k: "li", t: "entreprise" },
      { k: "li", t: "rôle et permissions" },
      { k: "li", t: "historique de connexion" },
      { k: "li", t: "actions réalisées sur la plateforme" },
      { k: "li", t: "logs de sécurité et d’utilisation" },
      { k: "h3", t: "2.3 Données des entreprises clientes" },
      { k: "li", t: "informations société" },
      { k: "li", t: "paramètres de recrutement" },
      { k: "li", t: "configurations des campagnes" },
      { k: "li", t: "critères d’évaluation définis dans la plateforme" },
      { k: "h2", t: "3. FINALITÉS DES TRAITEMENTS" },
      { k: "p", t: "Les données sont traitées afin de permettre :" },
      { k: "li", t: "la mise en relation entre candidats et recruteurs," },
      { k: "li", t: "la gestion des campagnes de recrutement," },
      { k: "li", t: "l’évaluation et la structuration des candidatures," },
      { k: "li", t: "la génération de synthèses et outils d’aide à la décision," },
      { k: "li", t: "l’amélioration du fonctionnement de la plateforme," },
      { k: "li", t: "la sécurité et la prévention des abus." },
      { k: "h2", t: "4. UTILISATION DE L’INTELLIGENCE ARTIFICIELLE" },
      { k: "p", t: "La plateforme Helpify repose sur des technologies d’intelligence artificielle permettant :" },
      { k: "li", t: "d’analyser les CV et réponses candidats," },
      { k: "li", t: "de générer des questions adaptées," },
      { k: "li", t: "de produire des synthèses et résumés," },
      { k: "li", t: "de structurer les informations issues des échanges." },
      { k: "p", t: "L’IA constitue un outil d’assistance à l’évaluation et ne prend aucune décision de recrutement." },
      { k: "h2", t: "5. ABSENCE DE DÉCISION AUTOMATISÉE" },
      { k: "p", t: "Aucune décision produisant des effets juridiques ou significatifs pour un candidat n’est prise de manière exclusivement automatisée." },
      { k: "p", t: "La décision finale appartient exclusivement à l’entreprise cliente." },
      { k: "h2", t: "6. DONNÉES AUDIO ET TRANSCRIPTIONS" },
      { k: "p", t: "Les échanges peuvent inclure des enregistrements audio." },
      { k: "p", t: "Ces données sont :" },
      { k: "li", t: "transcrites automatiquement," },
      { k: "li", t: "stockées dans l’espace sécurisé de la plateforme," },
      { k: "li", t: "accessibles uniquement selon les droits définis par le client." },
      { k: "p", t: "Les recruteurs n’ont accès qu’aux éléments configurés (transcription, synthèse, données structurées)." },
      { k: "h2", t: "7. CONSERVATION DES DONNÉES" },
      { k: "p", t: "Les données sont conservées selon les durées suivantes :" },
      { k: "li", t: "Candidats non retenus : jusqu’à 24 mois après dernier contact, sauf suppression anticipée" },
      { k: "li", t: "Données utilisateurs (recruteurs) : durée du contrat + période de sécurité" },
      { k: "li", t: "Logs techniques : durée strictement nécessaire à la sécurité et conformité" },
      { k: "h2", t: "8. SOUS-TRAITANTS ET INFRASTRUCTURE" },
      { k: "p", t: "Pour fournir le service, Helpify peut faire appel à des prestataires techniques (hébergement, stockage, traitement automatisé, intelligence artificielle)." },
      { k: "p", t: "Ces prestataires sont soumis à des obligations strictes de confidentialité et de sécurité." },
      { k: "p", t: "Les données peuvent être traitées via des infrastructures, dans le respect des garanties appropriées prévues par le RGPD." },
      { k: "h2", t: "9. SÉCURITÉ DES DONNÉES" },
      { k: "p", t: "Helpify met en œuvre des mesures techniques et organisationnelles appropriées afin de garantir :" },
      { k: "li", t: "la confidentialité des données," },
      { k: "li", t: "leur intégrité," },
      { k: "li", t: "leur disponibilité," },
      { k: "li", t: "la protection contre les accès non autorisés." },
      { k: "h2", t: "10. DROITS DES PERSONNES" },
      { k: "p", t: "Toute personne concernée dispose des droits suivants :" },
      { k: "li", t: "droit d’accès" },
      { k: "li", t: "droit de rectification" },
      { k: "li", t: "droit d’effacement" },
      { k: "li", t: "droit à la limitation du traitement" },
      { k: "li", t: "droit d’opposition" },
      { k: "li", t: "droit à la portabilité des données" },
      { k: "p", t: "Les demandes peuvent être adressées à : support@helpify-ai.fr" },
      { k: "h2", t: "11. MESURE D’AUDIENCE DU SITE ET COOKIES" },
      { k: "h3", t: "11.1 Mesure sans cookie" },
      { k: "p", t: "Le site helpify-ai.fr utilise Vercel Web Analytics, un outil de mesure d’audience fourni par Vercel Inc., afin de connaître la fréquentation du site (nombre de visiteurs, pages consultées, provenance du trafic) et d’en améliorer le contenu." },
      { k: "p", t: "Cet outil ne dépose aucun cookie sur le terminal du visiteur et ne permet pas de le suivre d’un site à un autre. Le visiteur est reconnu à l’aide d’un identifiant calculé à partir de sa requête, qui est réinitialisé chaque jour : il ne permet ni de l’identifier, ni de reconstituer sa navigation d’un jour à l’autre." },
      { k: "p", t: "Les informations suivantes peuvent être enregistrées pour chaque page consultée :" },
      { k: "li", t: "l’adresse de la page consultée et la page d’origine," },
      { k: "li", t: "la date et l’heure de la visite," },
      { k: "li", t: "le pays, la région et la ville approximatifs," },
      { k: "li", t: "le type d’appareil, le système d’exploitation et le navigateur." },
      { k: "p", t: "Ces informations ne servent qu’à produire des statistiques agrégées." },
      { k: "h3", t: "11.2 Google Analytics, avec votre accord" },
      { k: "p", t: "Avec votre accord uniquement, le site utilise également Google Analytics, un service de mesure d’audience de Google. Il permet de mieux comprendre l’usage du site : pages consultées, durée des visites, parcours entre les pages, provenance du trafic et actions réalisées, comme l’envoi du formulaire de contact." },
      { k: "p", t: "Pour cela, deux cookies sont déposés sur votre terminal (« _ga » et « _ga_ » suivi d’un identifiant) afin de reconnaître un même navigateur d’une visite à l’autre. Ils sont conservés au maximum 13 mois, et les données détaillées qui s’y rattachent au maximum 14 mois." },
      { k: "p", t: "Aucun cookie n’est déposé et aucune donnée n’est envoyée à Google tant que vous n’avez pas accepté. Vous pouvez refuser sans conséquence sur votre navigation, et revenir sur votre choix à tout moment avec le lien « Gérer les cookies » situé en bas de chaque page. Votre choix est mémorisé dans le stockage local de votre navigateur pendant 6 mois." },
      { k: "p", t: "Ces données peuvent être traitées par Google en dehors de l’Union européenne, notamment aux États-Unis, dans le respect des garanties appropriées prévues par le RGPD." },
      { k: "p", t: "Pour toute question relative à ces mesures, vous pouvez écrire à : support@helpify-ai.fr" },
      { k: "h2", t: "12. ÉVOLUTION DE LA POLITIQUE" },
      { k: "p", t: "La présente politique peut être modifiée à tout moment afin de refléter :" },
      { k: "li", t: "les évolutions légales," },
      { k: "li", t: "les évolutions techniques de la plateforme," },
      { k: "li", t: "les évolutions fonctionnelles du service." },
      { k: "p", t: "La version applicable est celle publiée sur la plateforme au moment de l’utilisation." },
    ],
  },
  "cgu": {
    slug: "cgu",
    title: "Conditions générales d'utilisation",
    description: "Conditions dans lesquelles les candidats accèdent au service Helpify et l'utilisent.",
    updated: "Dernière mise à jour : 07/06/2025",
    blocks: [
      { k: "h3", t: "ARTICLE 1 – OBJET" },
      { k: "p", t: "Les présentes Conditions Générales d’Utilisation (ci-après les « CGU ») ont pour objet de définir les conditions dans lesquelles les candidats accèdent et utilisent la plateforme Helpify dans le cadre d’un processus de recrutement mis en œuvre par une entreprise cliente de Helpify." },
      { k: "p", t: "L’utilisation du Service implique l’acceptation pleine et entière des présentes CGU." },
      { k: "p", t: "En utilisant le Service, le candidat reconnaît également avoir pris connaissance de la Politique de confidentialité et des informations relatives à l’utilisation de l’intelligence artificielle mises à sa disposition avant le démarrage des échanges." },
      { k: "h3", t: "ARTICLE 2 – DESCRIPTION DU SERVICE" },
      { k: "p", t: "Helpify est une solution technologique utilisant des outils d’intelligence artificielle afin de faciliter les échanges entre les entreprises recruteuses et les candidats." },
      { k: "p", t: "Dans le cadre d’un processus de recrutement, le Service peut notamment permettre :" },
      { k: "li", t: "de présenter des informations relatives à l’entreprise et au poste ;" },
      { k: "li", t: "de répondre aux questions du candidat ;" },
      { k: "li", t: "de recueillir des informations relatives au parcours, aux compétences, aux expériences et aux motivations du candidat ;" },
      { k: "li", t: "de générer des synthèses destinées à faciliter l’analyse des candidatures par les recruteurs." },
      { k: "p", t: "Le candidat reconnaît échanger avec une intelligence artificielle et non avec un recruteur humain." },
      { k: "p", t: "Helpify constitue un outil d’assistance au recrutement. Le Service ne prend aucune décision d’embauche, de refus ou de sélection. Toute décision relative à une candidature demeure de la seule responsabilité de l’entreprise recruteuse." },
      { k: "h3", t: "ARTICLE 3 – CONDITIONS D’ACCÈS" },
      { k: "p", t: "L’accès au Service s’effectue au moyen d’un lien transmis par l’entreprise recruteuse ou mis à disposition dans le cadre d’une campagne de recrutement." },
      { k: "p", t: "Le Service est réservé aux personnes âgées d’au moins dix-huit (18) ans ou disposant de la capacité légale nécessaire pour participer à un processus de recrutement." },
      { k: "p", t: "Certaines fonctionnalités complémentaires pourront, le cas échéant, nécessiter la création d’un compte utilisateur. Les modalités applicables seront alors précisées au moment de leur mise à disposition." },
      { k: "h3", t: "ARTICLE 4 – ENGAGEMENTS DU CANDIDAT" },
      { k: "p", t: "Le candidat s’engage à :" },
      { k: "li", t: "fournir des informations exactes, sincères et à jour ;" },
      { k: "li", t: "répondre personnellement aux questions posées ;" },
      { k: "li", t: "utiliser le Service conformément à sa finalité de recrutement ;" },
      { k: "li", t: "respecter les présentes CGU." },
      { k: "p", t: "Le candidat s’interdit notamment :" },
      { k: "li", t: "d’usurper l’identité d’un tiers ;" },
      { k: "li", t: "de fournir volontairement des informations trompeuses ou inexactes ;" },
      { k: "li", t: "d’utiliser des logiciels, scripts, robots ou outils d’automatisation pour interagir avec le Service ;" },
      { k: "li", t: "de tenter de contourner, perturber ou compromettre le fonctionnement du Service ;" },
      { k: "li", t: "de procéder à des opérations d’ingénierie inverse, de décompilation ou d’extraction du fonctionnement de l’intelligence artificielle ;" },
      { k: "li", t: "de tenter de manipuler les instructions internes du système d’intelligence artificielle (« prompt injection ») ;" },
      { k: "li", t: "d’utiliser le Service à des fins frauduleuses, illicites ou étrangères au recrutement." },
      { k: "h3", t: "ARTICLE 5 – RÈGLES DE CONDUITE" },
      { k: "p", t: "Le candidat s’engage à adopter un comportement respectueux dans le cadre des échanges réalisés via le Service." },
      { k: "p", t: "Sont notamment interdits :" },
      { k: "li", t: "les propos injurieux, diffamatoires ou menaçants ;" },
      { k: "li", t: "les contenus haineux ou discriminatoires ;" },
      { k: "li", t: "les contenus illicites ;" },
      { k: "li", t: "les contenus manifestement sans lien avec le processus de recrutement." },
      { k: "p", t: "Helpify se réserve le droit de suspendre ou interrompre immédiatement l’accès au Service en cas de violation des présentes dispositions." },
      { k: "h3", t: "ARTICLE 6 – ANALYSE DES ÉCHANGES" },
      { k: "p", t: "Dans le cadre du fonctionnement du Service, les informations communiquées par le candidat peuvent faire l’objet d’un traitement automatisé afin de générer des synthèses, analyses ou restitutions destinées à l’entreprise recruteuse." },
      { k: "p", t: "Lorsque le parcours le prévoit, le candidat peut consulter, corriger ou valider la synthèse générée avant sa transmission au recruteur." },
      { k: "p", t: "Le candidat reconnaît que les résultats générés par l’intelligence artificielle peuvent comporter des approximations ou imprécisions." },
      { k: "p", t: "Ces résultats constituent uniquement des éléments d’assistance à l’analyse des candidatures." },
      { k: "h3", t: "ARTICLE 7 – DONNÉES AUDIO" },
      { k: "p", t: "Lorsque le Service comprend des échanges vocaux, les enregistrements audio peuvent être transcrits et analysés afin de permettre le fonctionnement du Service." },
      { k: "p", t: "Les recruteurs n’ont pas nécessairement accès aux enregistrements audio. Selon la configuration du processus de recrutement, seules les transcriptions, synthèses ou informations restituées peuvent leur être communiquées." },
      { k: "p", t: "Les données audio sont conservées pendant la durée nécessaire au processus de recrutement concerné et, sauf instruction contraire de l’entreprise recruteuse responsable du traitement, pendant une durée maximale de vingt-quatre (24) mois." },
      { k: "p", t: "Les modalités détaillées de traitement des données sont précisées dans la Politique de confidentialité." },
      { k: "h3", t: "ARTICLE 8 – PROPRIÉTÉ INTELLECTUELLE" },
      { k: "p", t: "L’ensemble des éléments composant le Service, notamment les logiciels, interfaces, bases de données, contenus, marques, logos et technologies d’intelligence artificielle, est protégé par les dispositions relatives à la propriété intellectuelle." },
      { k: "p", t: "Ils demeurent la propriété exclusive de Helpify ou de ses partenaires." },
      { k: "p", t: "Aucun droit de propriété n’est transféré au candidat au titre de l’utilisation du Service." },
      { k: "p", t: "Le candidat autorise Helpify à traiter les contenus et informations communiqués dans le cadre du fonctionnement du Service, de l’analyse des candidatures et de l’amélioration des fonctionnalités de la plateforme, conformément à la Politique de confidentialité applicable." },
      { k: "h3", t: "ARTICLE 9 – ABSENCE DE GARANTIE ET LIMITATION DE RESPONSABILITÉ" },
      { k: "p", t: "Helpify met en œuvre les moyens raisonnables nécessaires au bon fonctionnement du Service." },
      { k: "p", t: "Toutefois, Helpify ne garantit pas :" },
      { k: "li", t: "l’obtention d’un entretien ;" },
      { k: "li", t: "l’obtention d’un emploi ;" },
      { k: "li", t: "l’aboutissement favorable d’une candidature ;" },
      { k: "li", t: "l’exactitude absolue des analyses ou synthèses générées." },
      { k: "p", t: "Helpify ne pourra être tenu responsable :" },
      { k: "li", t: "des décisions prises par l’entreprise recruteuse ;" },
      { k: "li", t: "des informations inexactes fournies par le candidat ;" },
      { k: "li", t: "des difficultés liées à la qualité de la connexion internet ;" },
      { k: "li", t: "des erreurs résultant d’un bruit de fond, d’une mauvaise qualité audio, d’un accent ou d’une formulation ambiguë ;" },
      { k: "li", t: "de l’indisponibilité temporaire du Service." },
      { k: "h3", t: "ARTICLE 10 – MODIFICATION DES CGU" },
      { k: "p", t: "Helpify peut modifier les présentes CGU à tout moment afin notamment de tenir compte de l’évolution du Service, de la réglementation applicable ou de ses pratiques opérationnelles." },
      { k: "p", t: "La version applicable est celle en vigueur à la date d’utilisation du Service." },
      { k: "h3", t: "ARTICLE 11 – ALTERNATIVES AU SERVICE" },
      { k: "p", t: "L’utilisation du Service peut être proposée dans le cadre du processus de recrutement défini par l’entreprise recruteuse." },
      { k: "p", t: "Les modalités alternatives de candidature, lorsqu’elles existent, sont définies par l’entreprise qui recrute." },
      { k: "p", t: "Le candidat est invité à se rapprocher directement de celle-ci pour connaître les éventuelles modalités alternatives disponibles." },
      { k: "h3", t: "ARTICLE 12 – DROIT APPLICABLE" },
      { k: "p", t: "Les présentes CGU sont soumises au droit français." },
      { k: "p", t: "Tout litige relatif à leur interprétation ou à leur exécution sera soumis aux juridictions compétentes conformément à la réglementation applicable." },
    ],
  },
};
